apiVersion: v2
name: user-management
description: A Helm chart for User Management Microservice
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: configmap
    version: "0.0.1"
    repository: "file://../configmap"
  - name: secrets
    version: "0.0.1"
    repository: "file://../secrets"
  - name: mongodb
    version: "0.0.1"
    repository: "file://../mongodb"